### PR TITLE
Use icons instead of text for permissions

### PR DESCRIPTION
**Pull request by Thor77**
permission_icons

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
how about accessibility?

**Comment by Thor77** [comment]
oh, i didn't think about it from that point of view.
Do you think some hover-texts for the icons are enough?
Or do you generally dislike the idea of using icons for permissions?

**Comment by ThomasWaldmann** [comment]
iirc, img alt attrs are mandatory for that. hover texts are likely useful also.

**Comment by pguth** [comment]
I think the icon selection is good. Alt-texts should suffice imho.

**Comment by Thor77** [comment]
added title-attr to icons for hover-text.
it seems like the alt-attr doesn't have any affect for the i-tag: i tried viewing the page with `lynx` but neither the icons nor the alt-text appeared.

**Comment by ThomasWaldmann** [comment]
yeah, alt might work only for img.

**Comment by Thor77** [comment]
What's about this XStatic-Stuff (i'm currently just using boostrap-CDN)?
It seems like the [XStatic-Font-Awesome](https://github.com/stackforge/xstatic-font-awesome) package is quite outdated...

**Comment by NotANormalNerd** [comment]
I am also not in the favour of those xstatic packages. The idea behind them is okay, but without the ecosystem it is just point blank useless. And the advantage is minor.

**Comment by Thor77** [comment]
It had some advantages for security, if you didn't rly trust your CDN.
But since at least Firefox + Chrome support [Subresource Integrity](https://hacks.mozilla.org/2015/09/subresource-integrity-in-firefox-43/), that's not a problem anymore.

**Comment by pguth** [comment]
Don't forget about the [`crossorigin` attribute](https://hacks.mozilla.org/2015/09/subresource-integrity-in-firefox-43/)! \o/

**Comment by ThomasWaldmann** [comment]
crossorigin anonymous looks nice.

**Pull request merged**
